0 ^iMain_Tmp @!
: _TABLEINIT 0.00000000 0 -1 }fInjectorNutrientMix InitTable ;
_TABLEINIT
FORGET _TABLEINIT
: _TABLEINIT 0.00000000 0 -1 }fInjectorVolumeTotalizer InitTable ;
_TABLEINIT
FORGET _TABLEINIT
: _TABLEINIT 0.00000000 0 -1 }fInjectorVolumeTotalizer_Yesterday InitTable ;
_TABLEINIT
FORGET _TABLEINIT
: _TABLEINIT 0 0 -1 }nInjectorDisplayNumber_Tmp InitTable ;
_TABLEINIT
FORGET _TABLEINIT
: _TABLEINIT 0 0 -1 }nInjectorDisplayPtr_Tmp InitTable ;
_TABLEINIT
FORGET _TABLEINIT
: _TABLEINIT 1 0 -1 }uiRecipeProportional InitTable ;
_TABLEINIT
FORGET _TABLEINIT
\ ""DOWNLOAD_COMPRESSION_OFF
